service: api-porta-admin-tindin
useDotenv: true

provider:
  name: aws
  memorySize: 2048
  timeout: 300
  runtime: nodejs10.x
  stage: production
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "ses:SendEmail"
      Resource:
        "*"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
        - "execute-api:Invoke"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

custom:
  serverless-offline:
    lambdaPort: 4000
    httpPort: 4001
  
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
