const ErrorTypesEnum = {
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TIMEOUT_CONNECT_BITCOIN_API: 'TIMEOUT_CONNECT_BITCOIN_API',
  NETWORK_ERROR_API: 'NETWORK_ERROR_API'
}

module.exports = {
  ErrorTypesEnum
}
