image: node:14.17.0

cache:
  untracked: true
  key:
    files:
      - package.json
  paths:
    - node_modules/

stages:
  - build
  - quality
  - security
  - staging_deploy
  - production_deploy
  - docs
  - gitlab_release    

build:
  stage: build
  script:
    - npm i
    - npm run test